/* Generated By:JJTree: Do not edit this line. ASTConjGraphPattern.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTConjGraphPattern extends SimpleNode {
	public ASTConjGraphPattern(int id) {
		super(id);
	}

	public ASTConjGraphPattern(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=dd35513929abc0d71456f4583aefae9e (do not edit this line) */
