/* Generated By:JJTree: Do not edit this line. ASTEncodeForURI.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTEncodeForURI extends SimpleNode {
	public ASTEncodeForURI(int id) {
		super(id);
	}

	public ASTEncodeForURI(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=1b9f96a7b4fc52d3696daf70de5ef0c4 (do not edit this line) */
