/* Generated By:JJTree: Do not edit this line. ASTGraphGraphPattern.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTGraphGraphPattern extends SimpleNode {
	public ASTGraphGraphPattern(int id) {
		super(id);
	}

	public ASTGraphGraphPattern(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=1275fdb3b76d813e7d64c06d526e3efe (do not edit this line) */
