/* Generated By:JJTree: Do not edit this line. ASTIsNumeric.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTIsNumeric extends SimpleNode {
	public ASTIsNumeric(int id) {
		super(id);
	}

	public ASTIsNumeric(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=918e8e4f94c3cdc4b0e9e44248056ab2 (do not edit this line) */
