/* Generated By:JJTree: Do not edit this line. ASTLangMatches.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTLangMatches extends SimpleNode {
	public ASTLangMatches(int id) {
		super(id);
	}

	public ASTLangMatches(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=9945aa26e0a10e8cfbc206915be5b612 (do not edit this line) */
