/* Generated By:JJTree: Do not edit this line. ASTOptionalGraphPattern.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTOptionalGraphPattern extends SimpleNode {
	public ASTOptionalGraphPattern(int id) {
		super(id);
	}

	public ASTOptionalGraphPattern(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=c16605f9d23e3650d345e0e2135c4711 (do not edit this line) */
