/* Generated By:JJTree: Do not edit this line. ASTQuadsNotTriples.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTQuadsNotTriples extends SimpleNode {
	public ASTQuadsNotTriples(int id) {
		super(id);
	}

	public ASTQuadsNotTriples(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=b24401910140f44c7bf1c7e31e1f6d80 (do not edit this line) */
