/* Generated By:JJTree: Do not edit this line. ASTSTRUUID.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTSTRUUID extends SimpleNode {
	public ASTSTRUUID(int id) {
		super(id);
	}

	public ASTSTRUUID(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=1163328747a30cdf86a9c79030af4b83 (do not edit this line) */
