/* Generated By:JJTree: Do not edit this line. ASTTriplesSameSubject.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTTriplesSameSubject extends SimpleNode {
	public ASTTriplesSameSubject(int id) {
		super(id);
	}

	public ASTTriplesSameSubject(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=2b81a53f15156a9e454b41564ed2de4d (do not edit this line) */
