/* Generated By:JJTree: Do not edit this line. ASTTriplesSameSubjectPath.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTTriplesSameSubjectPath extends SimpleNode {
	public ASTTriplesSameSubjectPath(int id) {
		super(id);
	}

	public ASTTriplesSameSubjectPath(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=4609611aa116b0e7407e72c2be49b48d (do not edit this line) */
